{
 "title": "Centralized Monitoring",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "jenkins_directory",
    "label": "Jenkins Directory",
    "query": "label_values({component_type=\"job\"}, directory)"
   },
   {
    "name": "jira_filter",
    "label": "Jira Filter",
    "query": "label_values({component_type=\"issue\"}, filter)"
   },
   {
    "name": "jira_user",
    "label": "Jira User",
    "query": "label_values({component_type=\"jira_nb_issues\", filter=\"$jira_filter\"}, assignee)"
   }
  ]
 },
 "panels": [
  { "title": "Global Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "content": "<h2 style=\"text-align:center\">GitHub</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Jenkins</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Gerrit</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Gitlab</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Jira</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Confluence</h2>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 1 },
   "content": "<h2 style=\"text-align:center\">Openstack</h2>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "github" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jenkins_mono_project" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "gitlab" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jira" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  { "title": "Jenkins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Jobs",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{component_type=\"job\", directory=\"$jenkins_directory\", mutable=\"true\"}"
    }
   ]
  },
  { "title": "Jira", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Nb issues",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "{component_type=\"jira_nb_issues\", filter=\"$jira_filter\", assignee=\"$jira_user\"}"
    }
   ]
  },
  {
   "title": "Total Open issues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{component_type=\"jira_nb_issues\", filter=\"$jira_filter\", assignee=\"$jira_user\"}"
    }
   ]
  },
  {
   "title": "Today issues",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "{component_type=\"jira_nb_today_issues\", filter=\"$jira_filter\", assignee=\"$jira_user\"}"
    }
   ]
  },
  {
   "title": "Daily issues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{component_type=\"jira_nb_today_issues\", filter=\"$jira_filter\", assignee=\"$jira_user\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{component_type=\"issue\", filter=\"$jira_filter\", c_assignee=\"$jira_user\", mutable=\"true\"} or {component_type=\"issue\", filter=\"$jira_filter\", all=\"$jira_user\", mutable=\"true\"}"
    }
   ]
  }
 ]
}