# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause Clear License.
# SPDX-License-Identifier: BSD-3-Clause-Clear

centralizedMonitoring:
  replicaCount: 1
  #nameOverride:
  #fullnameOverride:

  image:
    repository: cmonitoring
    tag: 0.1.1
    pullPolicy: IfNotPresent

  serviceType: ClusterIP
  service:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  config:
    # Enables the configmap deployment with config.json and/or connectionSettings.json
    config:
      enabled: true
    connectionSettings:
      enabled: true

  securityContext:
    enabled: true
    # User 5555 is defined as the centralized-monitoring user in Dockerfile
    fsGroup: 5555
    runAsUser: 5555

  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 700Mi
  liveness: true
  readiness: true

  persistence:
    enabled: true
    storageClass:
      enabled: true
      name: "hostpath"
    size: 1Gi
    accessModes:
      - ReadWriteOnce

prometheus:
  serviceAccounts:
    alertmanager:
      create: false
    pushgateway:
      create: false
    nodeExporter:
      create: false
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      size: 5Gi
  # the target URL for the Prometheus extraScrapeConfig should be the same
  # as centralized-monitoring <kubernetes service>:<service port> generated
  extraScrapeConfigs: |
    - job_name: cmonitoring
      metrics_path: /api/metrics
      scrape_interval: 60s
      static_configs:
        - targets:
            - centralized-monitoring

grafana:
  adminUser: admin
  adminPassword: admin
  pluginsSideCar:
    enabled: false
  ingress:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: "http://cmonitoring-prometheus-server"
        access: proxy
        isDefault: true
  SetDashboard:
    enabled: false
