# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause Clear License.
# SPDX-License-Identifier: BSD-3-Clause-Clear

apiVersion: v1
kind: Service
metadata:
  name: {{ template "centralizedMonitoring.name" . }}
  labels: {{- include "centralizedMonitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.centralizedMonitoring.serviceType }}
  ports:
    {{- range .Values.centralizedMonitoring.service }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
  {{- include "centralizedMonitoring.selectorLabels" . | nindent 4 }}
